version: "3.7"

services: 
    
    app:
        container_name: my_app
        build: .
        command: yarn dev
        volumes: 
            - .:/usr/src/app
        ports: 
            - "3333:3333"